/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminActions: typeof import('./src/components/action/AdminActions.vue')['default']
    AkCircleCheck: typeof import('@kalimahapps/vue-icons/ak')['AkCircleCheck']
    AkGithubFill: typeof import('@kalimahapps/vue-icons/ak')['AkGithubFill']
    AkHomeAlt1: typeof import('@kalimahapps/vue-icons/ak')['AkHomeAlt1']
    AkSignOut: typeof import('@kalimahapps/vue-icons/ak')['AkSignOut']
    AnOutlinedFileSync: typeof import('@kalimahapps/vue-icons/an')['AnOutlinedFileSync']
    BsListTask: typeof import('@kalimahapps/vue-icons/bs')['BsListTask']
    BxColumns: typeof import('@kalimahapps/vue-icons/bx')['BxColumns']
    BxSolidEditAlt: typeof import('@kalimahapps/vue-icons/bx')['BxSolidEditAlt']
    CaCloudLogging: typeof import('@kalimahapps/vue-icons/ca')['CaCloudLogging']
    CaPassword: typeof import('@kalimahapps/vue-icons/ca')['CaPassword']
    CaUserAdmin: typeof import('@kalimahapps/vue-icons/ca')['CaUserAdmin']
    CdRefresh: typeof import('@kalimahapps/vue-icons/cd')['CdRefresh']
    CdSync: typeof import('@kalimahapps/vue-icons/cd')['CdSync']
    ChPlus: typeof import('@kalimahapps/vue-icons/ch')['ChPlus']
    CoMoon: typeof import('@kalimahapps/vue-icons/co')['CoMoon']
    ConfirmModal: typeof import('./src/components/ConfirmModal.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DeGoogleOriginal: typeof import('@kalimahapps/vue-icons/de')['DeGoogleOriginal']
    DeMysqlOriginal: typeof import('@kalimahapps/vue-icons/de')['DeMysqlOriginal']
    DeMysqlOriginalWordmark: typeof import('@kalimahapps/vue-icons/de')['DeMysqlOriginalWordmark']
    DePostgresqlOriginal: typeof import('@kalimahapps/vue-icons/de')['DePostgresqlOriginal']
    DePostgresqlOriginalWordmark: typeof import('@kalimahapps/vue-icons/de')['DePostgresqlOriginalWordmark']
    FeDatabase: typeof import('@kalimahapps/vue-icons/fe')['FeDatabase']
    FlTextBulletListSquareSearch: typeof import('@kalimahapps/vue-icons/fl')['FlTextBulletListSquareSearch']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GlCollapseLeft: typeof import('@kalimahapps/vue-icons/gl')['GlCollapseLeft']
    GlTaskDone: typeof import('@kalimahapps/vue-icons/gl')['GlTaskDone']
    HiLanguage: typeof import('@kalimahapps/vue-icons/hi')['HiLanguage']
    LuSortAsc: typeof import('@kalimahapps/vue-icons/lu')['LuSortAsc']
    LuSortDesc: typeof import('@kalimahapps/vue-icons/lu')['LuSortDesc']
    MdOutlinedWbSunny: typeof import('@kalimahapps/vue-icons/md')['MdOutlinedWbSunny']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OauthIcon: typeof import('./src/components/OauthIcon.vue')['default']
    ReDeleteBin7Line: typeof import('@kalimahapps/vue-icons/re')['ReDeleteBin7Line']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SourceConnection: typeof import('./src/components/SourceConnection.vue')['default']
    SourceTypeIcon: typeof import('./src/components/SourceTypeIcon.vue')['default']
    SyncActions: typeof import('./src/components/action/SyncActions.vue')['default']
    TiOutlineCloudStorage: typeof import('@kalimahapps/vue-icons/ti')['TiOutlineCloudStorage']
    VsFolderTypeMongodb: typeof import('@kalimahapps/vue-icons/vs')['VsFolderTypeMongodb']
  }
}
